/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../../../common";
import type {
  Lockable,
  LockableInterface,
} from "../../../../../../../../lib/protocol/packages/core/contracts/common/implementation/Lockable";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506000805460ff19166001179055603f80602a6000396000f3fe6080604052600080fdfea2646970667358221220d5093d90524a605b4da5ca578bea9136fd1c0f037d004177f5a42f5da6c16b0864736f6c63430008110033";

type LockableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LockableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Lockable__factory extends ContractFactory {
  constructor(...args: LockableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Lockable> {
    return super.deploy(overrides || {}) as Promise<Lockable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Lockable {
    return super.attach(address) as Lockable;
  }
  override connect(signer: Signer): Lockable__factory {
    return super.connect(signer) as Lockable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LockableInterface {
    return new utils.Interface(_abi) as LockableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Lockable {
    return new Contract(address, _abi, signerOrProvider) as Lockable;
  }
}
