/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../../common";

export interface OracleAncillaryInterfaceInterface extends utils.Interface {
  functions: {
    "getPrice(bytes32,uint256,bytes)": FunctionFragment;
    "hasPrice(bytes32,uint256,bytes)": FunctionFragment;
    "requestPrice(bytes32,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getPrice" | "hasPrice" | "requestPrice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPrice",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPrice",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestPrice",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export interface OracleAncillaryInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OracleAncillaryInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hasPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    requestPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getPrice(
    identifier: PromiseOrValue<BytesLike>,
    time: PromiseOrValue<BigNumberish>,
    ancillaryData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hasPrice(
    identifier: PromiseOrValue<BytesLike>,
    time: PromiseOrValue<BigNumberish>,
    ancillaryData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  requestPrice(
    identifier: PromiseOrValue<BytesLike>,
    time: PromiseOrValue<BigNumberish>,
    ancillaryData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    requestPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestPrice(
      identifier: PromiseOrValue<BytesLike>,
      time: PromiseOrValue<BigNumberish>,
      ancillaryData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
