/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as skinnyOptimisticOracleSol from "./SkinnyOptimisticOracle.sol";
export type { skinnyOptimisticOracleSol };
