/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as common from "./common";
export type { common };
import type * as dataVerificationMechanism from "./data-verification-mechanism";
export type { dataVerificationMechanism };
import type * as optimisticOracle from "./optimistic-oracle";
export type { optimisticOracle };
