/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OptimisticOracleInterface__factory } from "./OptimisticOracleInterface__factory";
export { SkinnyOptimisticOracleInterface__factory } from "./SkinnyOptimisticOracleInterface__factory";
