/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OptimisticOracleInterface } from "./OptimisticOracleInterface";
export type { SkinnyOptimisticOracleInterface } from "./SkinnyOptimisticOracleInterface";
